In [ ]:
# Numpy -2 Vigneshwar Day-7 

#### Finding standard deviation for a array

In [1]:
import numpy as np
x1=[8.116,8.125,8.125,8.129,8.130,8.137,8.137,8.141,8.136,8.146]
np.std(x1)

0.008423775875461286

#### Finding mean of the series

In [2]:
import numpy as np
x=[8.112,8.118,8.124,8.130,8.136,8.137,8.138,8.139,8.137,8.141]
np.mean(x)

8.1312

 #### program to perform matrix operations using numpy arrays.

In [6]:
import numpy as np
a=np.array([[1,2],[2,1]])
b=np.array([[3,4],[4,3]])
r1=np.add(a,b)
r2=a-b
print(r1)
print(r2)

[[4 6]
 [6 4]]
[[-2 -2]
 [-2 -2]]


#### program to perform matrix multiplication using numpy arrays

In [7]:
import numpy as np
a=[[2,4],[6,8]]
b=[[1,3],[5,7]]
print(np.matmul(a,b))

[[22 34]
 [46 74]]


#### program to find transpose of a matrix using numpy arrays

In [9]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=a.transpose()
print(b)

[[1 3]
 [2 4]]


#### program to convert an one dimensional array into a two dimensional array using numpy.

In [16]:
import numpy as np
# 1-D array having elements [1 2 3 4 5 6 7 8]
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Now we can convert this 1-D array into 2-D in two ways

# 1. having dimension 4 x 2
arr1 = arr.reshape(4, 2)
print ('After reshaping having dimension 4x2:')
print (arr1)
print ('\n')

# 2. having dimension 2 x 4
arr2 = arr.reshape(2, 4)
print ('After reshaping having dimension 2x4:')
print (arr2)
print ('\n')


After reshaping having dimension 4x2:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


After reshaping having dimension 2x4:
[[1 2 3 4]
 [5 6 7 8]]


