# Day-8 Numpy part-3 Vigneshwar 07/12/2022

#### Conversion of binary numpy array to boolean numpy array

In [4]:
import numpy as np
a=np.array([1,0,1,1,0])
b=a.astype(bool)
print(b)

[ True False  True  True False]


#### Conversion of one datatype to another

In [5]:
import numpy as np
a=np.array([1.4, 7.4, 6.0, 2.1])
b=a.astype(int)
print(b)

[1 7 6 2]


#### program to perform horizontal stack and vertical stack of numpy array

In [8]:
import numpy as np
a=np.array([10,20,30])
b=np.hstack(a)
c=np.vstack(a)
print('Horizontal stack')
print(b)
print('Vertical stack')
print(c)

Horizontal stack
[10 20 30]
Vertical stack
[[10]
 [20]
 [30]]


#### numpy program to generate a sequence of numbers from 0 to 50 with intervals of 2 numbers

In [9]:
import numpy as np
a=np.arange(0,50,2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


#### numpy program to get the position where the elements of two numpy arrays match

In [10]:
import numpy as np
a=np.array([2,3,5,5])
b=np.array([2,4,5,6])
print(np.where(a==b))

(array([0, 2], dtype=int64),)


#### a numpy program to count equally spaced number within a specific range

In [11]:
import numpy as np
a=np.count_nonzero(np.linspace(2,3))
print(a)

50


#### python program to find sine and cosine of an angle using numpy

In [12]:
import numpy as np
x=np.sin(np.pi/2)
y=np.cos(np.pi)
print(x)
print(y)

1.0
-1.0


#### a numpy program to generate a sequence of random numbers in normal distribution

In [13]:
import numpy as np
from numpy import random
a=np.random.normal(size=3)
print(a)

[-0.65151912 -1.62265226  0.51757578]


#### a program to perform mathematical functions using numpy for exponents, log, square roots and cubes of an array

In [14]:
import numpy as np
a=np.array([1, 8, 4])
print(np.exp(a))
print(np.log(a))
print(np.sqrt(a))
print(np.power(a,3))

[2.71828183e+00 2.98095799e+03 5.45981500e+01]
[0.         2.07944154 1.38629436]
[1.         2.82842712 2.        ]
[  1 512  64]


In [ ]:
####  Done by Vigneshwar.B